name: capitan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07981216185726225
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f9fc'
    - '#dec3e2'
    - '#b7a287'
    - '#1c1c1c'
    - '#776911'
  brandStrength: 0.8657606185879558
  lightness: 0.7617791192606091
  saturation: 0.7963710792828351
  rhythmicContrast: 0.7913641571067274
purpose: []
